### ISSUE TITLE
Disable audit?

### ISSUE THREAD

**Issue by rakateja** [securitybunker/databunker#18]
Hi @stremovsky, thank you for the great project. 
Is it possible to disable audit feature? as in our case we don't need it at the moment. Thank you.

**Comment by stremovsky** [comment]
Hello,

I added an option to disable audit feature.

The changes were already merged and new containers were rebuild.

You can see the changes here:
https://github.com/securitybunker/databunker/commit/f1bb37c4d1f2a154cb839a882a73791a2ddde667

PS. If it is possible, I will love to chat with you to understand how you use Databunker.
https://calendly.com/stremovsky/30min?month=2023-12

Best regards!
Yuli
