### ISSUE TITLE
PostgreSQL backend?

### ISSUE THREAD

**Issue by beeing** [securitybunker/databunker#9]
Hi @stremovsky, thank you for such as great project.
It definitely helps many developers on PII compliance.

Just wondering is there a plan to support alternate DB like PostgreSQL? It is easier for self-hosting since there's existing tech stacks for this.

Thanks in advance!

**Comment by stremovsky** [comment]
Hello

I do support PostgreSQL in the Databunker PRO. It is used for multi-
tenancy implemented using PostgreSQL row-based security feature.

If the community wants PostgreSQL support I can port the code to
the regular version of Databunker.

Best regards,
Yuli

**Comment by stremovsky** [comment]
I committed the postgresql support:
https://github.com/securitybunker/databunker/blob/master/src/storage/pgsql-storage.go

I will need to do some tests to make sure it is working.

**Comment by stremovsky** [comment]
You will be able now to run Databunker with PostgreSQL

First run: `./generate-pgsql-env-files.sh` script to generate `.env` directory and files with sectets.

Run `docker-compose -f docker-compose-pgsql.yml up` to start postgresql container and databunker together.

Best of luck!

**Comment by beeing** [comment]
Thanks @stremovsky, let me try it out and report if there's any issues.

**Comment by rakateja** [comment]
hey @beeing, have you tried Databunker with PostgreSQL in production? how was it?

**Comment by stremovsky** [comment]
@rakateja I am running it for quite a long time and I see no problems.

Thanks
